spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://nacos-mysql:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user.0=root
db.password.0=123456

nacos.core.auth.enabled=false
